### ISSUE TITLE
`get name(): string` should support property access and more complex matches.

### ISSUE THREAD

**Issue by yjhmelody** [willemneal/visitor-as#10]
It's better to support @foo.bar for `Decorator`
Though as compiler has a problem to handle decorator syntax. But `visitor-as` could do better.

```ts

@list.list // how to match it ?
@list // is ok
export class Foo {
  a: u8;
  b: bool;
  i: i32;
}
```

Maybe a better signature is `get name(): Array<string>`

**Comment by yjhmelody** [comment]
Hi guys! Any idea about it ? 

If decorator can support more complex match, it's also ok. Such as support regexp to match a decorator signature. 
If we can do it, we can handle different decorators easily.

**Comment by yjhmelody** [comment]
@willemneal

**Comment by willemneal** [comment]
Sorry for the long delay.  I think this should definitely be doable.  I think we should change it to be a match function and then default to matching on a string.
