### ISSUE TITLE
Bump AssemblyScript peerDependency version

### ISSUE THREAD

**Issue by mehtaphysical** [willemneal/visitor-as#13]
Right now the AssemblyScript peerDependency is set to version `^0.13.3`. Should bump this to a higher version or make the acceptable versions less restrictive.

Right now with npm v7 installing visitor-as and AssemblyScript `0.18.x`,  for example, fails without the force flag:

```
npm ERR!   dev assemblyscript@"^0.18.13" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer assemblyscript@"^0.13.3" from visitor-as@0.4.0
```

Once AssemblyScript is `1.x.x` this will be less of an issue because of how npm resolves valid versions. Whenever the major version is 0, the `^0.13.3` syntax will only allow version above `0.13.3` and under `0.14.0`.

**Comment by willemneal** [comment]
fixed by #18
